project:
  type: website

website:
  title: "Quarto Presentations"
  repo-url: https://github.com/TheZetner/quarto-presentations
  repo-actions: [issue]
  navbar:
    left:
      - href: index.qmd
        text: Presentation List
    right:
      - icon: github
        href: https://github.com/TheZetner/quarto-presentations

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



