project:
  type: website

website:
  title: "Quarto Presentations"
  navbar:
    left:
      - href: index.qmd
        text: Presntation List

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



